const seed={employees:[{id:1,name:'Emil Nieminen',phone:'040 123 4567'},{id:2,name:'Matti Virtanen',phone:'040 234 5678'},{id:3,name:'Jari Laaksonen',phone:'040 345 6789'}],sites:[{id:1,name:'As Oy Kissankello'},{id:2,name:'As Oy Koivurinne'},{id:3,name:'Varasto / kalustohuolto'}],entries:[{id:1,employeeId:1,date:'2026-07-13',siteId:1,hours:8,note:'Parvekkeiden suojaukset',status:'pending'},{id:2,employeeId:1,date:'2026-07-14',siteId:1,hours:8,note:'Hiekkapuhalluksen valmistelu',status:'pending'},{id:3,employeeId:1,date:'2026-07-15',siteId:1,hours:7.5,note:'Betonikorjaukset',status:'pending'},{id:4,employeeId:2,date:'2026-07-13',siteId:2,hours:8,note:'Telineiden tarkastus',status:'pending'},{id:5,employeeId:2,date:'2026-07-14',siteId:2,hours:8,note:'Julkisivutyöt',status:'pending'},{id:6,employeeId:3,date:'2026-07-13',siteId:1,hours:7.5,note:'Maalaustyöt',status:'approved'}]};
let db=JSON.parse(localStorage.getItem('tuntivahti'))||structuredClone(seed),session=null,tab='hours',dialog='';
const app=document.querySelector('#app'),save=()=>localStorage.setItem('tuntivahti',JSON.stringify(db));
const emp=id=>db.employees.find(x=>x.id===id),site=id=>db.sites.find(x=>x.id===id),sum=a=>a.reduce((n,x)=>n+Number(x.hours),0),initials=n=>n.split(' ').map(x=>x[0]).slice(0,2).join('');
const date=d=>new Intl.DateTimeFormat('fi-FI',{weekday:'short',day:'numeric',month:'numeric'}).format(new Date(d+'T12:00:00'));
const labels={draft:'Luonnos',pending:'Odottaa hyväksyntää',approved:'Hyväksytty',rejected:'Korjattava'};
function render(){if(!session)return login();app.innerHTML=`<header class="topbar"><div class="brand">✓ Tuntivahti</div><button class="logout" onclick="logout()">Kirjaudu ulos</button></header><main class="container">${session.role==='worker'?worker():manager()}</main>${dialog}`}
function login(){app.innerHTML=`<main class="login"><section class="login-card"><div class="logo">✓</div><div class="eyebrow" style="margin-top:20px">Tampereen Julkisivutekniikka Oy</div><h1>Tuntivahti</h1><p class="muted">Kirjaa työaika puhelimella. Työnjohto tarkistaa ja hyväksyy tunnit viikoittain.</p><div class="roles"><button class="role" onclick="session={role:'worker',id:1};render()"><strong>👷 Työntekijän demo</strong><span>Kirjaa ja lähetä viikon tunnit</span></button><button class="role" onclick="session={role:'manager'};render()"><strong>📋 Työnjohdon demo</strong><span>Tarkista tunnit ja hallitse perustietoja</span></button></div><p class="muted" style="font-size:12px;margin-top:22px">Ensimmäinen testiversio · tiedot tallentuvat tähän selaimeen</p></section></main>`}
function logout(){session=null;tab='hours';render()}
function worker(){const rows=db.entries.filter(x=>x.employeeId===session.id),total=sum(rows),pending=rows.some(x=>x.status==='pending'),approved=rows.length&&rows.every(x=>x.status==='approved');return `<div class="heading"><div><div class="eyebrow">${emp(session.id).name}</div><h1>Viikko 29</h1><p class="muted">13.–19.7.2026</p></div><button class="primary" onclick="entryDialog()">+ Lisää kirjaus</button></div><div class="stats"><div class="stat"><span>Kirjatut tunnit</span><strong>${total} h</strong></div><div class="stat"><span>Työpäiviä</span><strong>${new Set(rows.map(x=>x.date)).size}</strong></div><div class="stat"><span>Viikon tila</span><strong style="font-size:16px"><i class="status ${approved?'approved':pending?'pending':'draft'}">${approved?'Hyväksytty':pending?'Tarkistettavana':'Kesken'}</i></strong></div></div><div class="grid"><section class="card"><div class="card-head"><h2>Päiväkohtaiset kirjaukset</h2></div><div class="card-body entries">${rows.map(entryRow).join('')||'<p class="muted">Ei kirjauksia.</p>'}</div></section><aside class="card"><div class="card-head"><h2>Viikon yhteenveto</h2></div><div class="card-body">${db.sites.map(s=>{let h=sum(rows.filter(x=>x.siteId===s.id));return h?`<div class="summary"><span>${s.name}</span><strong>${h} h</strong></div>`:''}).join('')}<div class="summary"><strong>Yhteensä</strong><strong>${total} h</strong></div>${pending?'<div class="notice">Viikko on työnjohdon tarkistettavana.</div>':approved?'<div class="notice">Viikon tunnit on hyväksytty.</div>':`<button class="primary full" style="margin-top:18px" onclick="submitWeek()">Lähetä hyväksyttäväksi</button>`}</div></aside></div>`}
function entryRow(x){let parts=date(x.date).split(' ');return `<div class="entry"><div class="date"><strong>${parts[0]}</strong><span>${parts[1]}</span></div><div class="entry-main"><strong>${site(x.siteId).name}</strong><span>${x.note||'Ei lisätietoa'} · <i class="status ${x.status}">${labels[x.status]}</i></span></div><div class="hours">${x.hours} h</div><button class="remove" onclick="removeEntry(${x.id})">×</button></div>`}
function entryDialog(){dialog=`<div class="modal-wrap"><form class="modal" onsubmit="addEntry(event)"><h2>Lisää tuntikirjaus</h2><div class="form"><div class="field"><label>Päivä</label><input name="date" type="date" value="2026-07-17" required></div><div class="field"><label>Tunnit</label><input name="hours" type="number" min="0.5" max="24" step="0.5" value="8" required></div><div class="field wide"><label>Työmaa</label><select name="site">${db.sites.map(x=>`<option value="${x.id}">${x.name}</option>`)}</select></div><div class="field wide"><label>Työn kuvaus</label><textarea name="note"></textarea></div></div><div class="modal-actions"><button type="button" class="secondary" onclick="closeDialog()">Peruuta</button><button class="primary">Tallenna</button></div></form></div>`;render()}
function addEntry(e){e.preventDefault();let f=new FormData(e.target);db.entries.push({id:Date.now(),employeeId:session.id,date:f.get('date'),siteId:Number(f.get('site')),hours:Number(f.get('hours')),note:f.get('note'),status:'draft'});save();closeDialog()}
function removeEntry(id){db.entries=db.entries.filter(x=>x.id!==id);save();render()}function submitWeek(){db.entries.filter(x=>x.employeeId===session.id&&x.status==='draft').forEach(x=>x.status='pending');save();render()}function closeDialog(){dialog='';render()}
function manager(){return `<div class="heading"><div><div class="eyebrow">Työnjohto</div><h1>Tuntien tarkistus</h1><p class="muted">Viikko 29 · 13.–19.7.2026</p></div></div><nav class="tabs"><button class="tab ${tab==='hours'?'active':''}" onclick="setTab('hours')">Tuntien hyväksyntä</button><button class="tab ${tab==='employees'?'active':''}" onclick="setTab('employees')">Työntekijät</button><button class="tab ${tab==='sites'?'active':''}" onclick="setTab('sites')">Työmaat</button></nav>${tab==='hours'?reviews():tableView(tab)}`}
function setTab(x){tab=x;render()}
function reviews(){let groups=db.employees.map(e=>({e,rows:db.entries.filter(x=>x.employeeId===e.id)})).filter(x=>x.rows.length);return `<div class="stats"><div class="stat"><span>Odottaa tarkistusta</span><strong>${groups.filter(g=>g.rows.some(x=>x.status==='pending')).length}</strong></div><div class="stat"><span>Viikon tunnit</span><strong>${sum(db.entries)} h</strong></div><div class="stat"><span>Työntekijöitä</span><strong>${groups.length}</strong></div></div><div class="reviews">${groups.map(g=>`<article class="review"><div class="review-top"><div class="person"><div class="avatar">${initials(g.e.name)}</div><div><strong>${g.e.name}</strong><div class="muted">${new Set(g.rows.map(x=>x.date)).size} työpäivää</div></div></div><i class="status ${g.rows.every(x=>x.status==='approved')?'approved':'pending'}">${g.rows.every(x=>x.status==='approved')?'Hyväksytty':'Odottaa tarkistusta'}</i></div><div class="meta"><div><span>Tunnit</span><strong>${sum(g.rows)} h</strong></div><div><span>Työmaat</span><strong>${new Set(g.rows.map(x=>x.siteId)).size}</strong></div></div><div class="actions"><button class="danger" onclick="review(${g.e.id},'rejected')">Palauta korjattavaksi</button><button class="success" onclick="review(${g.e.id},'approved')">Hyväksy tunnit</button></div></article>`).join('')}</div>`}
function review(id,status){db.entries.filter(x=>x.employeeId===id).forEach(x=>x.status=status);save();render()}
function tableView(type){let people=type==='employees';let rows=people?db.employees:db.sites;return `<section class="card"><div class="card-head"><h2>${people?'Työntekijät':'Työmaat'}</h2><button class="primary" onclick="simpleDialog('${type}')">+ Lisää</button></div><div class="card-body table-wrap"><table class="table"><thead><tr><th>${people?'Nimi':'Työmaan nimi'}</th>${people?'<th>Puhelin</th>':''}<th>Tila</th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${x.name}</strong></td>${people?`<td>${x.phone}</td>`:''}<td><i class="status approved">Aktiivinen</i></td></tr>`).join('')}</tbody></table></div></section>`}
function simpleDialog(type){let people=type==='employees';dialog=`<div class="modal-wrap"><form class="modal" onsubmit="addSimple(event,'${type}')"><h2>Lisää ${people?'työntekijä':'työmaa'}</h2><div class="field"><label>${people?'Nimi':'Työmaan nimi'}</label><input name="name" required></div>${people?'<div class="field" style="margin-top:14px"><label>Puhelin</label><input name="phone" required></div>':''}<div class="modal-actions"><button type="button" class="secondary" onclick="closeDialog()">Peruuta</button><button class="primary">Tallenna</button></div></form></div>`;render()}
function addSimple(e,type){e.preventDefault();let f=new FormData(e.target);if(type==='employees')db.employees.push({id:Date.now(),name:f.get('name'),phone:f.get('phone')});else db.sites.push({id:Date.now(),name:f.get('name')});save();closeDialog()}
render();
