const LITTERAS=[
 {code:'1100',name:'Purkutyöt'},{code:'1200',name:'Maanrakennus'},{code:'2100',name:'Anturat, mantteloinnit'},
 {code:'3000',name:'Runkorakenteet'},{code:'3620',name:'Parvekkeet, muotitus ja valu'},{code:'3650',name:'Elementtiparvekkeet'},
 {code:'3760',name:'Vesikaton puurunkotyöt'},{code:'3765',name:'Sisäänkäynnin katokset'},{code:'3770',name:'Parvekekatot'},
 {code:'3775',name:'Räystäiden jatko'},{code:'5036',name:'Pellit'},{code:'5150',name:'Vedenpoistot'},
 {code:'5546',name:'Rappaus'},{code:'5550',name:'Elastiset saumaukset'},{code:'5560',name:'Julkisivujen ranka- ja levytyö'},
 {code:'5590',name:'Eristerappaus'},{code:'5600',name:'Levyrappaus'},{code:'5750',name:'Yksikkösidonnaiset'},
 {code:'5805',name:'Hiekkapuhallus ja korkeapainepesu'},{code:'5810',name:'Ylitasoitustyöt'},{code:'5815',name:'Maalaus ja pinnoitus'},
 {code:'8150',name:'Aitaus ja kulkusuojaus'},{code:'8160',name:'Aputyöt, suojaus ja siivous'},{code:'8180',name:'Telineet ja nostimet'},
 {code:'8200',name:'Työmaan perustaminen ja lopettaminen'}
];
const seed={
 employees:[{id:1,name:'Emil Nieminen',phone:'040 123 4567'},{id:2,name:'Matti Virtanen',phone:'040 234 5678'},{id:3,name:'Jari Laaksonen',phone:'040 345 6789'}],
 sites:[
  {id:1,name:'As Oy Kissankello'},{id:2,name:'As Oy Koivurinne'},{id:3,name:'Varasto / kalustohuolto'}
 ],
 entries:[
  {id:1,employeeId:1,date:'2026-07-13',siteId:1,litteraCode:'8160',start:'07:00',end:'10:00',note:'Parvekkeiden suojaukset',status:'pending'},
  {id:2,employeeId:1,date:'2026-07-13',siteId:1,litteraCode:'3620',start:'10:00',end:'13:00',note:'Paikkauskorjaukset',status:'pending'},
  {id:3,employeeId:1,date:'2026-07-13',siteId:1,litteraCode:'5810',start:'13:00',end:'15:30',note:'Tasoitustyöt',status:'pending'},
  {id:4,employeeId:1,date:'2026-07-14',siteId:1,litteraCode:'3620',start:'07:00',end:'15:30',note:'Betonikorjaukset',status:'pending'},
  {id:5,employeeId:2,date:'2026-07-13',siteId:2,litteraCode:'8180',start:'07:00',end:'15:30',note:'Telineiden tarkastus',status:'pending'},
  {id:6,employeeId:3,date:'2026-07-13',siteId:1,litteraCode:'5815',start:'07:00',end:'15:00',note:'Maalaustyöt',status:'approved'}
 ],
 dayNotes:[]
};
let db=JSON.parse(localStorage.getItem('tuntivahti-v3'))||structuredClone(seed),session=null,tab='hours',dialog='';
db.dayNotes??=[];
const app=document.querySelector('#app'),save=()=>localStorage.setItem('tuntivahti-v3',JSON.stringify(db));
const emp=id=>db.employees.find(x=>x.id===id),site=id=>db.sites.find(x=>x.id===id),initials=n=>n.split(' ').map(x=>x[0]).slice(0,2).join('');
const littera=code=>LITTERAS.find(x=>x.code===String(code))||{code:String(code),name:'Tuntematon littera'};
const litteraOptions=()=>LITTERAS.map(x=>`<option value="${x.code}">${x.code} – ${x.name}</option>`).join('');
const dayNote=(employeeId,date)=>db.dayNotes.find(x=>x.employeeId===employeeId&&x.date===date);
const fmtDate=d=>new Intl.DateTimeFormat('fi-FI',{weekday:'short',day:'numeric',month:'numeric'}).format(new Date(d+'T12:00:00'));
const labels={draft:'Luonnos',pending:'Odottaa hyväksyntää',approved:'Hyväksytty',rejected:'Korjattava'};
function duration(x){const [sh,sm]=x.start.split(':').map(Number),[eh,em]=x.end.split(':').map(Number);return Math.max(0,(eh*60+em-sh*60-sm)/60)}
function dayRows(rows){return Object.entries(rows.reduce((a,x)=>((a[x.date]??=[]).push(x),a),{})).sort(([a],[b])=>a.localeCompare(b))}
function dayGross(rows){return rows.reduce((n,x)=>n+duration(x),0)}
function dayBreak(rows){return dayGross(rows)>6?.5:0}
function dayNet(rows){return Math.max(0,dayGross(rows)-dayBreak(rows))}
function totalNet(rows){return dayRows(rows).reduce((n,[,r])=>n+dayNet(r),0)}
function num(n){return n.toLocaleString('fi-FI',{minimumFractionDigits:n%1?1:0,maximumFractionDigits:2})}
function render(){if(!session)return login();const roleName=session.role==='worker'?emp(session.id).name:session.role==='admin'?'Pääkäyttäjä':'Työnjohto';const content=session.role==='worker'?worker():session.role==='admin'?admin():manager();app.innerHTML=`<header class="topbar"><div class="brand">✓ Tuntivahti</div><div><span style="margin-right:14px">${roleName}</span><button class="logout" onclick="logout()">Kirjaudu ulos</button></div></header><main class="container">${content}</main>${dialog}`}
function login(){app.innerHTML=`<main class="login"><section class="login-card"><div class="logo">✓</div><div class="eyebrow" style="margin-top:20px">Tampereen Julkisivutekniikka Oy</div><h1>Tuntivahti</h1><p class="muted">Kirjaa työajat, hyväksy viikot ja seuraa kustannuksia litteroittain.</p><div class="roles"><button class="role" onclick="session={role:'worker',id:1};render()"><strong>👷 Työntekijän demo</strong><span>Kirjaa työmaa, ajat ja littera</span></button><button class="role" onclick="session={role:'manager'};render()"><strong>📋 Työnjohdon demo</strong><span>Tarkista ja hyväksy työntekijöiden viikot</span></button><button class="role" onclick="session={role:'admin'};tab='dashboard';render()"><strong>⚙️ Pääkäyttäjän demo</strong><span>Hallitse kokonaisuutta ja avaa kuukausiraportit</span></button></div></section></main>`}
function logout(){session=null;tab='hours';render()}
function worker(){const rows=db.entries.filter(x=>x.employeeId===session.id),pending=rows.some(x=>x.status==='pending'),approved=rows.length&&rows.every(x=>x.status==='approved');return `<div class="heading"><div><div class="eyebrow">Omat tunnit</div><h1>Viikko 29</h1><p class="muted">13.–19.7.2026</p></div><button class="primary" onclick="entryDialog()">+ Lisää kirjaus</button></div><div class="stats"><div class="stat"><span>Maksettavat tunnit</span><strong>${num(totalNet(rows))} h</strong></div><div class="stat"><span>Työpäiviä</span><strong>${dayRows(rows).length}</strong></div><div class="stat"><span>Viikon tila</span><strong style="font-size:16px"><i class="status ${approved?'approved':pending?'pending':'draft'}">${approved?'Hyväksytty':pending?'Tarkistettavana':'Kesken'}</i></strong></div></div><div class="grid"><section class="card"><div class="card-head"><h2>Päivien työerittely</h2></div><div class="card-body entries">${dayRows(rows).map(dayBlock).join('')||'<p class="muted">Ei kirjauksia.</p>'}</div></section><aside class="card"><div class="card-head"><h2>Viikon yhteenveto</h2></div><div class="card-body">${dayRows(rows).map(([d,r])=>`<div class="summary"><span>${fmtDate(d)}</span><strong>${num(dayNet(r))} h</strong></div>`).join('')}<div class="summary"><strong>Yhteensä</strong><strong>${num(totalNet(rows))} h</strong></div>${pending?'<div class="notice">Viikko on työnjohdon tarkistettavana.</div>':approved?'<div class="notice">Viikon tunnit on hyväksytty.</div>':`<button class="primary full" style="margin-top:18px" onclick="submitWeek()">Lähetä viikko hyväksyttäväksi</button>`}</div></aside></div>`}
function dayBlock([d,rows]){const note=dayNote(session.id,d);return `<div style="border:1px solid #e5eaf1;border-radius:13px;overflow:hidden"><div style="padding:12px 14px;background:#f8fafc;display:flex;justify-content:space-between"><strong>${fmtDate(d)}</strong><strong>${num(dayNet(rows))} h</strong></div>${note?`<div class="notice" style="margin:10px 12px"><strong>Työnjohdon huomautus:</strong> ${note.text}</div>`:''}${rows.map(entryRow).join('')}</div>`}
function entryRow(x){const l=littera(x.litteraCode);return `<div class="entry" style="border:0;border-top:1px solid #edf1f6;border-radius:0"><div class="date"><strong>${x.start}</strong><span>${x.end}</span></div><div class="entry-main"><strong>${l.code} – ${l.name}</strong><span>${site(x.siteId).name}${x.note?' · '+x.note:''} · <i class="status ${x.status}">${labels[x.status]}</i></span></div><div class="hours">${num(duration(x))} h</div><button class="remove" onclick="removeEntry(${x.id})">×</button></div>`}
function yesterday(){const d=new Date();d.setDate(d.getDate()-1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function lastEntryFor(date){return db.entries.filter(x=>x.employeeId===session.id&&x.date===date).sort((a,b)=>a.end.localeCompare(b.end)).at(-1)}
function entryDialog(chosenDate=yesterday()){const previous=lastEntryFor(chosenDate),start=previous?.end||'07:00',siteId=previous?.siteId||db.sites[0].id;dialog=`<div class="modal-wrap"><form class="modal" onsubmit="addEntry(event)"><h2>Lisää kirjaus</h2><div class="form"><div class="field"><label>Päivä</label><input name="date" type="date" value="${chosenDate}" onchange="entryDialog(this.value)" required></div><div class="field"><label>Työmaa</label><select name="site">${db.sites.map(x=>`<option value="${x.id}" ${x.id===siteId?'selected':''}>${x.name}</option>`)}</select></div><div class="field"><label>Aloitusaika</label><input name="start" type="time" value="${start}" required></div><div class="field"><label>Lopetusaika</label><input name="end" type="time" required></div><div class="field wide"><label>Litteranumero / tehty työ</label><select name="litteraCode">${litteraOptions()}</select></div><div class="field wide"><label>Lisätieto (valinnainen)</label><textarea name="note"></textarea></div></div><div class="modal-actions"><button type="button" class="secondary" onclick="closeDialog()">Peruuta</button><button class="secondary" name="next" value="1">Tallenna ja lisää seuraava</button><button class="primary">Tallenna</button></div></form></div>`;render()}
function overlaps(x){return db.entries.some(r=>r.employeeId===x.employeeId&&r.date===x.date&&x.start<r.end&&x.end>r.start)}
function addEntry(e){e.preventDefault();const addNext=e.submitter?.value==='1',f=new FormData(e.target),x={id:Date.now(),employeeId:session.id,date:f.get('date'),siteId:Number(f.get('site')),litteraCode:f.get('litteraCode'),start:f.get('start'),end:f.get('end'),note:f.get('note'),status:'draft'};if(duration(x)<=0){alert('Lopetusajan pitää olla aloitusajan jälkeen.');return}if(overlaps(x)){alert('Kirjaus menee päällekkäin saman päivän aiemman kirjauksen kanssa.');return}db.entries.push(x);save();if(addNext)entryDialog(x.date);else closeDialog()}
function removeEntry(id){db.entries=db.entries.filter(x=>x.id!==id);save();render()}function submitWeek(){db.entries.filter(x=>x.employeeId===session.id&&['draft','rejected'].includes(x.status)).forEach(x=>x.status='pending');save();render()}function closeDialog(){dialog='';render()}
function manager(){return `<div class="heading"><div><div class="eyebrow">Työnjohto</div><h1>Tuntien tarkistus</h1><p class="muted">Työntekijän ilmoittamat työmaat, litterat ja ajat</p></div></div><nav class="tabs"><button class="tab ${tab==='hours'?'active':''}" onclick="setTab('hours')">Tuntien hyväksyntä</button><button class="tab ${tab==='employees'?'active':''}" onclick="setTab('employees')">Työntekijät</button><button class="tab ${tab==='sites'?'active':''}" onclick="setTab('sites')">Työmaat</button></nav>${tab==='hours'?reviews():tableView(tab)}`}
function setTab(x){tab=x;render()}
function reviews(){const groups=db.employees.map(e=>({e,rows:db.entries.filter(x=>x.employeeId===e.id)})).filter(x=>x.rows.length);return `<div class="stats"><div class="stat"><span>Odottaa tarkistusta</span><strong>${groups.filter(g=>g.rows.some(x=>x.status==='pending')).length}</strong></div><div class="stat"><span>Maksettavat tunnit</span><strong>${num(groups.reduce((n,g)=>n+totalNet(g.rows),0))} h</strong></div><div class="stat"><span>Työntekijöitä</span><strong>${groups.length}</strong></div></div><div class="reviews">${groups.map(reviewCard).join('')}</div>`}
function reviewCard(g){return `<article class="review"><div class="review-top"><div class="person"><div class="avatar">${initials(g.e.name)}</div><div><strong>${g.e.name}</strong><div class="muted">${dayRows(g.rows).length} työpäivää · ${num(totalNet(g.rows))} h</div></div></div><i class="status ${g.rows.every(x=>x.status==='approved')?'approved':'pending'}">${g.rows.every(x=>x.status==='approved')?'Hyväksytty':'Odottaa tarkistusta'}</i></div><div style="margin:17px 0">${dayRows(g.rows).map(([d,r])=>managerDay(g.e.id,d,r)).join('')}</div><div class="actions"><button class="danger" onclick="review(${g.e.id},'rejected')">Palauta työntekijälle</button><button class="success" onclick="review(${g.e.id},'approved')">Hyväksy viikko</button></div></article>`}
function managerDay(employeeId,d,rows){const note=dayNote(employeeId,d);return `<div style="padding:11px 0;border-top:1px solid #edf1f6"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center"><strong>${fmtDate(d)} · ${num(dayNet(rows))} h</strong><button class="secondary" style="padding:7px 10px" onclick="noteDialog(${employeeId},'${d}')">${note?'Muokkaa huomautusta':'+ Lisää huomautus'}</button></div><div class="muted" style="font-size:13px;margin-top:5px">${rows.map(x=>{const l=littera(x.litteraCode);return `${x.start}–${x.end} ${site(x.siteId).name}: ${l.code} – ${l.name}`}).join('<br>')}</div>${note?`<div class="notice" style="margin-top:9px"><strong>Huomautus:</strong> ${note.text}</div>`:''}</div>`}
function noteDialog(employeeId,date){const note=dayNote(employeeId,date);dialog=`<div class="modal-wrap"><form class="modal" onsubmit="saveDayNote(event)"><h2>${note?'Muokkaa':'Lisää'} huomautusta</h2><p class="muted">${emp(employeeId).name} · ${fmtDate(date)}</p><input type="hidden" name="employeeId" value="${employeeId}"><input type="hidden" name="date" value="${date}"><div class="field"><label>Työnjohdon huomautus</label><textarea name="text" required autofocus>${note?.text||''}</textarea></div><div class="modal-actions">${note?'<button type="button" class="danger" onclick="deleteDayNote('+employeeId+',\''+date+'\')">Poista</button>':''}<button type="button" class="secondary" onclick="closeDialog()">Peruuta</button><button class="primary">Tallenna</button></div></form></div>`;render()}
function saveDayNote(e){e.preventDefault();const f=new FormData(e.target),employeeId=Number(f.get('employeeId')),date=f.get('date'),text=f.get('text').trim(),old=dayNote(employeeId,date);if(old)old.text=text;else db.dayNotes.push({id:Date.now(),employeeId,date,text,author:'Työnjohto',createdAt:new Date().toISOString()});save();closeDialog()}
function deleteDayNote(employeeId,date){db.dayNotes=db.dayNotes.filter(x=>!(x.employeeId===employeeId&&x.date===date));save();closeDialog()}
function review(id,status){db.entries.filter(x=>x.employeeId===id).forEach(x=>x.status=status);save();render()}
function tableView(type){const people=type==='employees',rows=people?db.employees:db.sites;return `<section class="card"><div class="card-head"><h2>${people?'Työntekijät':'Työmaat'}</h2></div><div class="card-body table-wrap"><table class="table"><thead><tr><th>${people?'Nimi':'Työmaan nimi'}</th>${people?'<th>Puhelin</th>':''}<th>Tila</th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${x.name}</strong></td>${people?`<td>${x.phone}</td>`:''}<td><i class="status approved">Aktiivinen</i></td></tr>`).join('')}</tbody></table></div></section>`}
function admin(){return `<div class="heading"><div><div class="eyebrow">Pääkäyttäjä</div><h1>Yrityksen tuntihallinta</h1><p class="muted">Tampereen Julkisivutekniikka Oy · heinäkuu 2026</p></div></div><nav class="tabs"><button class="tab ${tab==='dashboard'?'active':''}" onclick="setTab('dashboard')">Yhteenveto</button><button class="tab ${tab==='reports'?'active':''}" onclick="setTab('reports')">Kuukausiraportit</button><button class="tab ${tab==='sites'?'active':''}" onclick="setTab('sites')">Työmaat</button><button class="tab ${tab==='employees'?'active':''}" onclick="setTab('employees')">Käyttäjät</button><button class="tab ${tab==='litteras'?'active':''}" onclick="setTab('litteras')">Litterat</button></nav>${tab==='dashboard'?adminDashboard():tab==='reports'?monthlyReports():tab==='litteras'?litteraTable():tableView(tab)}`}
function adminDashboard(){const rows=db.entries,pending=new Set(rows.filter(x=>x.status==='pending').map(x=>x.employeeId)).size;return `<div class="stats"><div class="stat"><span>Heinäkuun maksettavat tunnit</span><strong>${num(allNet(rows))} h</strong></div><div class="stat"><span>Hyväksyntää odottaa</span><strong>${pending}</strong></div><div class="stat"><span>Aktiiviset työmaat</span><strong>${db.sites.length}</strong></div></div><div class="grid"><section class="card"><div class="card-head"><h2>Mihin tunnit kohdistuvat?</h2><button class="primary" onclick="setTab('reports')">Avaa raportit</button></div><div class="card-body">${siteTotals(rows).map(x=>`<div class="summary"><span>${x.name}</span><strong>${num(x.hours)} h</strong></div>`).join('')}</div></section><aside class="card"><div class="card-head"><h2>Ohjelman hyöty</h2></div><div class="card-body"><p>✓ Tunnit valmiina laskutukseen työmaittain</p><p>✓ Palkkatunnit työntekijöittäin</p><p>✓ Kustannukset litteranumeroittain</p><p>✓ Laskun liite ilman käsin kokoamista</p><p>✓ Viikoittainen hyväksyntä ja huomautukset</p></div></aside></div>`}
function allNet(rows){return db.employees.reduce((n,e)=>n+totalNet(rows.filter(x=>x.employeeId===e.id)),0)}
function siteTotals(rows){return db.sites.map(s=>({name:s.name,hours:rows.filter(x=>x.siteId===s.id).reduce((n,x)=>n+duration(x),0)})).filter(x=>x.hours)}
function employeeTotals(rows){return db.employees.map(e=>({name:e.name,hours:totalNet(rows.filter(x=>x.employeeId===e.id))})).filter(x=>x.hours)}
function litteraTotals(rows){return LITTERAS.map(l=>({code:l.code,name:l.name,hours:rows.filter(x=>x.litteraCode===l.code).reduce((n,x)=>n+duration(x),0)})).filter(x=>x.hours)}
function monthlyReports(){const rows=db.entries;return `<div class="stats"><div class="stat"><span>Kirjattuja työvaiheita</span><strong>${rows.length}</strong></div><div class="stat"><span>Maksettavat tunnit</span><strong>${num(allNet(rows))} h</strong></div><div class="stat"><span>Käytettyjä litteroita</span><strong>${new Set(rows.map(x=>x.litteraCode)).size}</strong></div></div><div class="card" style="margin-bottom:22px"><div class="card-head"><div><h2>Kuukausiraportit · heinäkuu 2026</h2><div class="muted" style="font-size:13px;margin-top:4px">Valmiit yhteenvedot laskutukseen, palkanlaskentaan ja kustannusseurantaan</div></div><button class="primary" onclick="downloadCsv()">Lataa CSV taloushallintoon</button></div></div><div class="grid" style="margin-bottom:22px"><section class="card"><div class="card-head"><h2>Työmaittain · laskutus</h2></div><div class="card-body">${siteTotals(rows).map(x=>`<div class="summary"><span>${x.name}</span><strong>${num(x.hours)} h</strong></div>`).join('')}</div></section><section class="card"><div class="card-head"><h2>Työntekijöittäin · palkat</h2></div><div class="card-body">${employeeTotals(rows).map(x=>`<div class="summary"><span>${x.name}</span><strong>${num(x.hours)} h</strong></div>`).join('')}</div></section></div><section class="card" style="margin-bottom:22px"><div class="card-head"><h2>Litteroittain · kustannusseuranta</h2></div><div class="card-body table-wrap"><table class="table"><thead><tr><th>Littera</th><th>Työn nimi</th><th>Kirjatut tunnit</th></tr></thead><tbody>${litteraTotals(rows).map(x=>`<tr><td><strong>${x.code}</strong></td><td>${x.name}</td><td><strong>${num(x.hours)} h</strong></td></tr>`).join('')}</tbody></table></div></section><section class="card"><div class="card-head"><div><h2>Laskun liite · työaikaerittely</h2><div class="muted" style="font-size:13px;margin-top:4px">Nimi, päivämäärä, työmaa, littera ja työaika</div></div></div><div class="card-body table-wrap"><table class="table"><thead><tr><th>Päivä</th><th>Työntekijä</th><th>Työmaa</th><th>Littera</th><th>Aika</th><th>Tunnit</th></tr></thead><tbody>${rows.sort((a,b)=>a.date.localeCompare(b.date)).map(x=>{const l=littera(x.litteraCode);return `<tr><td>${fmtDate(x.date)}</td><td>${emp(x.employeeId).name}</td><td>${site(x.siteId).name}</td><td><strong>${l.code}</strong> – ${l.name}</td><td>${x.start}–${x.end}</td><td>${num(duration(x))} h</td></tr>`}).join('')}</tbody></table></div></section>`}
function litteraTable(){return `<section class="card"><div class="card-head"><div><h2>Litterarekisteri</h2><div class="muted" style="font-size:13px;margin-top:4px">TJT Litterat · taloushallinnon kustannuskohdistus</div></div></div><div class="card-body table-wrap"><table class="table"><thead><tr><th>Numero</th><th>Nimi</th><th>Tila</th></tr></thead><tbody>${LITTERAS.map(x=>`<tr><td><strong>${x.code}</strong></td><td>${x.name}</td><td><i class="status approved">Käytössä</i></td></tr>`).join('')}</tbody></table></div></section>`}
function downloadCsv(){const header=['Päivä','Työntekijä','Työmaa','Litteranumero','Litteran nimi','Alku','Loppu','Kirjatut tunnit','Tila'];const lines=[header,...db.entries.map(x=>{const l=littera(x.litteraCode);return [x.date,emp(x.employeeId).name,site(x.siteId).name,l.code,l.name,x.start,x.end,num(duration(x)),labels[x.status]]})];const csv='\ufeff'+lines.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\r\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='tuntivahti_kuukausiraportti_2026-07.csv';a.click();URL.revokeObjectURL(url)}
render();
