import React,{useEffect,useMemo,useState} from 'react';
import {supabase} from './main.jsx';

const roleNames={admin:'Pääkäyttäjä',foreman:'Työnjohtaja',worker:'Työntekijä'};
const today=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Europe/Helsinki'});
const hoursBetween=(start,end)=>{const [sh,sm]=start.slice(0,5).split(':').map(Number),[eh,em]=end.slice(0,5).split(':').map(Number);return Math.max(0,(eh*60+em-sh*60-sm)/60)};
const hoursLabel=value=>`${Number(value).toFixed(2).replace('.',',')} h`;

export default function App(){
 const [session,setSession]=useState(null),[profile,setProfile]=useState(null),[loading,setLoading]=useState(true),[passwordRecovery,setPasswordRecovery]=useState(false);
 useEffect(()=>{if(!supabase){setLoading(false);return}supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data:{subscription}}=supabase.auth.onAuthStateChange((event,s)=>{setSession(s);if(event==='PASSWORD_RECOVERY')setPasswordRecovery(true)});return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(!session){setProfile(null);return}supabase.from('profiles').select('id,full_name,role,organization_id,employer_id,organizations(name)').eq('id',session.user.id).single().then(({data,error})=>{if(error)console.error(error);setProfile(data)})},[session]);
 if(loading)return <ScreenMessage text="Ladataan…"/>;
 if(!supabase)return <ScreenMessage text="Supabase-yhteystiedot puuttuvat ympäristömuuttujista."/>;
 if(passwordRecovery)return <ResetPassword onDone={()=>setPasswordRecovery(false)}/>;
 if(!session)return <Login/>;
 if(!profile)return <ScreenMessage text="Ladataan käyttäjäprofiilia…"/>;
 return <Shell profile={profile} onLogout={()=>supabase.auth.signOut()}/>;
}

function Login(){
 const [email,setEmail]=useState('mika.viljanen0@gmail.com'),[password,setPassword]=useState(''),[forgot,setForgot]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e){e.preventDefault();setBusy(true);setError('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setError('Kirjautuminen epäonnistui. Tarkista sähköposti ja salasana.');setBusy(false)}
 async function sendReset(e){e.preventDefault();setBusy(true);setError('');setMessage('');const {error}=await supabase.auth.resetPasswordForEmail(email.trim().toLowerCase(),{redirectTo:window.location.origin});if(error)setError('Vaihtolinkin lähettäminen epäonnistui. Tarkista sähköpostiosoite.');else setMessage('Jos osoite kuuluu käyttäjälle, siihen lähetettiin salasanan vaihtolinkki.');setBusy(false)}
 return <main className="login"><form className="login-card" onSubmit={forgot?sendReset:submit}><div className="logo">✓</div><div className="eyebrow" style={{marginTop:20}}>Tampereen Julkisivutekniikka Oy</div><h1>{forgot?'Palauta salasana':'Tuntivahti'}</h1><p className="muted">{forgot?'Lähetämme sähköpostiisi turvallisen vaihtolinkin.':'Kirjaudu yrityksen tuntien ja työmaiden hallintaan.'}</p><div className="field" style={{marginTop:24}}><label>Sähköposti</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div>{!forgot&&<div className="field" style={{marginTop:14}}><label>Salasana</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></div>}{error&&<div className="notice error">{error}</div>}{message&&<div className="notice success-note">{message}</div>}<button className="primary full" style={{marginTop:18}} disabled={busy}>{busy?'Odota…':forgot?'Lähetä vaihtolinkki':'Kirjaudu'}</button><button type="button" className="text-button full" onClick={()=>{setForgot(!forgot);setError('');setMessage('')}}>{forgot?'Takaisin kirjautumiseen':'Unohtuiko salasana?'}</button></form></main>
}

function ResetPassword({onDone}){const [password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function save(e){e.preventDefault();setError('');if(password.length<8)return setError('Salasanassa pitää olla vähintään 8 merkkiä.');if(password!==confirm)return setError('Salasanat eivät vastaa toisiaan.');setBusy(true);const {error}=await supabase.auth.updateUser({password});if(error)setError(error.message);else onDone();setBusy(false)}return <main className="login"><form className="login-card" onSubmit={save}><div className="logo">✓</div><h1>Valitse uusi salasana</h1><p className="muted">Anna vähintään kahdeksan merkkiä pitkä salasana.</p><div className="field"><label>Uusi salasana</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength="8" required/></div><div className="field" style={{marginTop:14}}><label>Uusi salasana uudelleen</label><input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} minLength="8" required/></div>{error&&<div className="notice error">{error}</div>}<button className="primary full" style={{marginTop:18}} disabled={busy}>{busy?'Tallennetaan…':'Tallenna uusi salasana'}</button></form></main>}

function Shell({profile,onLogout}){
 const [tab,setTab]=useState(profile.role==='worker'?'hours':'dashboard');
 return <><header className="topbar"><div className="brand">✓ Tuntivahti</div><div><span className="user-label">{profile.full_name} · {roleNames[profile.role]}</span><button className="logout" onClick={onLogout}>Kirjaudu ulos</button></div></header><main className="container"><div className="heading"><div><div className="eyebrow">{roleNames[profile.role]}</div><h1>{profile.organizations?.name||'Tuntivahti'}</h1><p className="muted">Työaika kohdistetaan työmaanumerolle ja litteralle.</p></div></div>{profile.role==='admin'?<Admin profile={profile} tab={tab} setTab={setTab}/>:profile.role==='worker'?<Worker profile={profile} tab={tab} setTab={setTab}/>:<ScreenMessage text="Työnjohtajan hyväksyntänäkymä rakennetaan seuraavassa vaiheessa."/>}</main></>;
}

function Admin({profile,tab,setTab}){const tabs=[['dashboard','Yhteenveto'],['worksites','Työmaat'],['employees','Työntekijät'],['hours','Omat tunnit']];return <><NavTabs tabs={tabs} tab={tab} setTab={setTab}/>{tab==='dashboard'&&<Dashboard orgId={profile.organization_id} openWorksites={()=>setTab('worksites')}/>} {tab==='worksites'&&<Worksites orgId={profile.organization_id}/>} {tab==='employees'&&<Employees orgId={profile.organization_id}/>} {tab==='hours'&&<TimeEntries profile={profile}/>}</>}
function Worker({profile,tab,setTab}){return <><NavTabs tabs={[["hours","Omat tunnit"]]} tab={tab} setTab={setTab}/><TimeEntries profile={profile}/></>}
function NavTabs({tabs,tab,setTab}){return <nav className="tabs">{tabs.map(([key,label])=><button key={key} className={`tab ${tab===key?'active':''}`} onClick={()=>setTab(key)}>{label}</button>)}</nav>}

function Dashboard({orgId,openWorksites}){
 const [counts,setCounts]=useState({worksites:0,employers:0,litteras:0,employees:0});
 useEffect(()=>{Promise.all([supabase.from('worksites').select('*',{count:'exact',head:true}),supabase.from('employers').select('*',{count:'exact',head:true}),supabase.from('litteras').select('*',{count:'exact',head:true}),supabase.from('profiles').select('*',{count:'exact',head:true})]).then(rs=>setCounts({worksites:rs[0].count||0,employers:rs[1].count||0,litteras:rs[2].count||0,employees:rs[3].count||0}))},[orgId]);
 return <><div className="stats four"><Stat label="Työmaat" value={counts.worksites}/><Stat label="Työnantajayritykset" value={counts.employers}/><Stat label="Työntekijät" value={counts.employees}/><Stat label="Litterat" value={counts.litteras}/></div><section className="card"><div className="card-head"><h2>Tuotantopohja on yhdistetty</h2><button className="primary" onClick={openWorksites}>Lisää työmaa</button></div><div className="card-body"><p>✓ Oikea kirjautuminen toimii</p><p>✓ Organisaatio ja käyttäjärooli tulevat tietokannasta</p><p>✓ Työnantajat ja litterat tulevat yhteisestä rekisteristä</p><p>✓ Työmaa perustetaan vain kerran ja näkyy myöhemmin molemmissa ohjelmissa</p></div></section></>;
}
function Stat({label,value}){return <div className="stat"><span>{label}</span><strong>{value}</strong></div>}

function Employees({orgId}){
 const [rows,setRows]=useState([]),[employers,setEmployers]=useState([]),[fullName,setFullName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[role,setRole]=useState('worker'),[employerId,setEmployerId]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const [profilesResult,employersResult]=await Promise.all([supabase.from('profiles').select('id,full_name,email,role,active,employers(name)').order('full_name'),supabase.from('employers').select('id,name').eq('active',true).order('name')]);if(profilesResult.error||employersResult.error)setError(profilesResult.error?.message||employersResult.error?.message);else{setRows(profilesResult.data||[]);setEmployers(employersResult.data||[]);setEmployerId(current=>current||employersResult.data?.[0]?.id||'')}}
 useEffect(()=>{load()},[orgId]);
 function generatePassword(){setPassword(`Tunti${Math.floor(100000+Math.random()*900000)}!`)}
 async function addUser(event){event.preventDefault();setBusy(true);setError('');setMessage('');const {data,error}=await supabase.functions.invoke('create-user',{body:{fullName:fullName.trim(),email:email.trim().toLowerCase(),password,role,employerId}});if(error){let text=error.message;try{const body=await error.context.json();text=body.error||text}catch{}setError(text)}else{setMessage(`${data.fullName} lisättiin käyttäjäksi. Anna hänelle sähköposti ja väliaikainen salasana turvallisesti.`);setFullName('');setEmail('');setPassword('');setRole('worker');await load()}setBusy(false)}
 async function sendUserReset(row){if(!row.email)return setError('Käyttäjältä puuttuu sähköpostiosoite.');setError('');setMessage('');const {error}=await supabase.auth.resetPasswordForEmail(row.email,{redirectTo:window.location.origin});if(error)setError('Vaihtolinkin lähettäminen epäonnistui.');else setMessage(`Salasanan vaihtolinkki lähetettiin osoitteeseen ${row.email}.`)}
 return <div className="employee-layout"><section className="card"><div className="card-head"><div><h2>Lisää käyttäjä</h2><p className="muted compact">Luo työntekijälle tai työnjohtajalle oma kirjautumistunnus.</p></div></div><form className="card-body" onSubmit={addUser}><div className="field"><label>Nimi</label><input value={fullName} onChange={e=>setFullName(e.target.value)} required/></div><div className="field form-space"><label>Sähköposti</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className="form form-space"><div className="field"><label>Rooli</label><select value={role} onChange={e=>setRole(e.target.value)}><option value="worker">Työntekijä</option><option value="foreman">Työnjohtaja</option></select></div><div className="field"><label>Työnantajayritys</label><select value={employerId} onChange={e=>setEmployerId(e.target.value)} required>{employers.map(employer=><option key={employer.id} value={employer.id}>{employer.name}</option>)}</select></div></div><div className="field form-space"><label>Väliaikainen salasana</label><div className="password-row"><input value={password} onChange={e=>setPassword(e.target.value)} minLength="8" required/><button type="button" className="secondary" onClick={generatePassword}>Luo salasana</button></div><small className="muted">Vähintään 8 merkkiä. Anna salasana henkilölle turvallisesti.</small></div>{error&&<div className="notice error">{error}</div>}{message&&<div className="notice success-note">{message}</div>}<button className="primary full form-space" disabled={busy}>{busy?'Lisätään…':'Lisää käyttäjä'}</button></form></section><section className="card"><div className="card-head"><div><h2>Käyttäjät</h2><p className="muted compact">Työntekijät ja työnjohtajat samassa rekisterissä.</p></div></div><div className="card-body table-wrap"><table className="table"><thead><tr><th>Nimi</th><th>Sähköposti</th><th>Työnantaja</th><th>Rooli</th><th></th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.full_name}</strong></td><td>{row.email||'—'}</td><td>{row.employers?.name||'—'}</td><td>{roleNames[row.role]}</td><td><button className="secondary nowrap" onClick={()=>sendUserReset(row)} disabled={!row.email}>Lähetä vaihtolinkki</button></td></tr>)}</tbody></table>{!rows.length&&<p className="muted">Käyttäjiä ei ole vielä lisätty.</p>}</div></section></div>;
}

function Worksites({orgId}){
 const [rows,setRows]=useState([]),[number,setNumber]=useState(''),[name,setName]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const {data,error}=await supabase.from('worksites').select('id,number,name,status,created_at').order('number');if(error)setError(error.message);else setRows(data||[])}
 useEffect(()=>{load()},[orgId]);
 async function add(e){e.preventDefault();setBusy(true);setError('');const {error}=await supabase.from('worksites').insert({organization_id:orgId,number:number.trim(),name:name.trim(),status:'active'});if(error)setError(error.code==='23505'?'Työmaanumero on jo käytössä.':error.message);else{setNumber('');setName('');await load()}setBusy(false)}
 async function toggle(row){const next=row.status==='active'?'closed':'active';const {error}=await supabase.from('worksites').update({status:next,updated_at:new Date().toISOString()}).eq('id',row.id);if(error)setError(error.message);else load()}
 return <div className="grid"><section className="card"><div className="card-head"><h2>Lisää työmaa</h2></div><form className="card-body" onSubmit={add}><div className="field"><label>Työmaanumero</label><input value={number} onChange={e=>setNumber(e.target.value)} placeholder="Esim. 2612" required/></div><div className="field" style={{marginTop:14}}><label>Työmaan nimi</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Virallinen nimi" required/></div>{error&&<div className="notice error">{error}</div>}<button className="primary full" style={{marginTop:18}} disabled={busy}>{busy?'Tallennetaan…':'Tallenna työmaa'}</button></form></section><section className="card"><div className="card-head"><h2>Työmaarekisteri</h2></div><div className="card-body table-wrap"><table className="table"><thead><tr><th>Numero</th><th>Nimi</th><th>Tila</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.number}</strong></td><td>{r.name}</td><td><i className={`status ${r.status==='active'?'approved':'draft'}`}>{r.status==='active'?'Aktiivinen':'Suljettu'}</i></td><td><button className="secondary" onClick={()=>toggle(r)}>{r.status==='active'?'Sulje':'Avaa'}</button></td></tr>)}</tbody></table>{!rows.length&&<p className="muted">Työmaita ei ole vielä perustettu.</p>}</div></section></div>;
}

function TimeEntries({profile}){
 const [worksites,setWorksites]=useState([]),[litteras,setLitteras]=useState([]),[entries,setEntries]=useState([]),[workDate,setWorkDate]=useState(today()),[startTime,setStartTime]=useState('07:00'),[endTime,setEndTime]=useState('15:30'),[worksiteId,setWorksiteId]=useState(''),[litteraId,setLitteraId]=useState(''),[note,setNote]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function loadEntries(){const {data,error}=await supabase.from('time_entries').select('id,work_date,start_time,end_time,note,status,worksites(number,name),litteras(code,name)').eq('employee_id',profile.id).order('work_date',{ascending:false}).order('start_time',{ascending:false});if(error)setError(error.message);else setEntries(data||[])}
 useEffect(()=>{Promise.all([supabase.from('worksites').select('id,number,name,status').order('number'),supabase.from('litteras').select('id,code,name').eq('active',true).order('code')]).then(([w,l])=>{if(w.error||l.error)setError(w.error?.message||l.error?.message);else{setWorksites(w.data||[]);setLitteras(l.data||[]);setWorksiteId(w.data?.[0]?.id||'');setLitteraId(l.data?.[0]?.id||'')}});loadEntries()},[profile.id]);
 const dayEntries=useMemo(()=>entries.filter(entry=>entry.work_date===workDate).sort((a,b)=>a.start_time.localeCompare(b.start_time)),[entries,workDate]);
 const grossHours=useMemo(()=>dayEntries.reduce((sum,row)=>sum+hoursBetween(row.start_time,row.end_time),0),[dayEntries]);
 const paidHours=Math.max(0,grossHours-(grossHours>6?0.5:0));
 function applyDate(date){setWorkDate(date);const sameDay=entries.filter(e=>e.work_date===date).sort((a,b)=>b.end_time.localeCompare(a.end_time));setStartTime(sameDay[0]?.end_time?.slice(0,5)||'07:00');setEndTime('15:30');setMessage('');setError('')}
 async function save(addNext){
  setError('');setMessage('');if(!worksiteId||!litteraId)return setError('Valitse työmaa ja littera.');if(!endTime||endTime<=startTime)return setError('Päättymisajan pitää olla alkamisajan jälkeen.');
  const overlaps=dayEntries.some(e=>startTime<e.end_time.slice(0,5)&&endTime>e.start_time.slice(0,5));if(overlaps)return setError('Kirjaus menee päällekkäin saman päivän aiemman kirjauksen kanssa.');
  setBusy(true);const {error}=await supabase.from('time_entries').insert({organization_id:profile.organization_id,employee_id:profile.id,worksite_id:worksiteId,littera_id:litteraId,work_date:workDate,start_time:startTime,end_time:endTime,note:note.trim()||null,status:'draft'});if(error)setError(error.message);else{await loadEntries();setMessage(addNext?'Kirjaus tallennettu. Lisää seuraava työvaihe.':'Kirjaus tallennettu.');setNote('');if(addNext){setStartTime(endTime);setEndTime('')}}setBusy(false);
 }
 async function remove(id){if(!window.confirm('Poistetaanko tämä kirjaus?'))return;const {error}=await supabase.from('time_entries').delete().eq('id',id);if(error)setError(error.message);else loadEntries()}
 return <div className="hours-layout"><section className="card"><div className="card-head"><div><h2>Lisää kirjaus</h2><p className="muted compact">Täytä toteutunut työaika jälkikäteen.</p></div></div><div className="card-body"><div className="form"><div className="field"><label>Päivämäärä</label><input type="date" value={workDate} onChange={e=>applyDate(e.target.value)} required/></div><div className="field"><label>Työmaa</label><select value={worksiteId} onChange={e=>setWorksiteId(e.target.value)} required>{worksites.map(w=><option key={w.id} value={w.id}>{w.number} – {w.name}{w.status==='closed'?' (suljettu)':''}</option>)}</select></div><div className="field"><label>Alkoi</label><input type="time" value={startTime} onChange={e=>setStartTime(e.target.value)} required/></div><div className="field"><label>Päättyi</label><input type="time" value={endTime} onChange={e=>setEndTime(e.target.value)} required/></div><div className="field wide"><label>Littera / tehty työ</label><select value={litteraId} onChange={e=>setLitteraId(e.target.value)} required>{litteras.map(l=><option key={l.id} value={l.id}>{l.code} – {l.name}</option>)}</select></div><div className="field wide"><label>Lisätieto (valinnainen)</label><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Esim. A-talon parvekkeet"/></div></div>{error&&<div className="notice error">{error}</div>}{message&&<div className="notice success-note">{message}</div>}<div className="save-actions"><button className="secondary" disabled={busy} onClick={()=>save(false)}>Tallenna</button><button className="primary" disabled={busy} onClick={()=>save(true)}>{busy?'Tallennetaan…':'Tallenna ja lisää seuraava'}</button></div></div></section><section className="card"><div className="card-head"><div><h2>{new Date(`${workDate}T12:00:00`).toLocaleDateString('fi-FI',{weekday:'long',day:'numeric',month:'numeric',year:'numeric'})}</h2><p className="muted compact">Päivän kirjaukset</p></div><strong className="paid-total">{hoursLabel(paidHours)}</strong></div><div className="card-body"><div className="day-summary"><span>Työaika {hoursLabel(grossHours)}</span><span>{grossHours>6?'Ruokatauko vähennetty automaattisesti 0,50 h':'Ei ruokataukovähennystä'}</span></div><div className="entries">{dayEntries.map(row=><div className="entry" key={row.id}><div className="entry-time"><strong>{row.start_time.slice(0,5)}–{row.end_time.slice(0,5)}</strong><span>{hoursLabel(hoursBetween(row.start_time,row.end_time))}</span></div><div className="entry-main"><strong>{row.worksites.number} – {row.worksites.name}</strong><span>{row.litteras.code} – {row.litteras.name}{row.note?` · ${row.note}`:''}</span></div><i className="status draft">Luonnos</i><button className="remove" title="Poista" onClick={()=>remove(row.id)}>Poista</button></div>)}{!dayEntries.length&&<p className="muted">Tälle päivälle ei ole vielä kirjauksia.</p>}</div></div></section></div>;
}

function ScreenMessage({text}){return <main className="login"><div className="login-card"><div className="logo">✓</div><h2>{text}</h2></div></main>}
