export const languageOptions=[
  {value:'fi',label:'Suomi'},
  {value:'sq',label:'Shqip (albania)'},
  {value:'en',label:'English (englanti)'},
  {value:'uk',label:'Українська (ukraina)'},
];

const texts={
 fi:{worker:'Työntekijä',ownHours:'Omat tunnit',logout:'Kirjaudu ulos',monthHours:'Kuukauden maksettavat tunnit',thisMonth:'Tämä kuukausi',weekdays:['Ma','Ti','Ke','To','Pe','La','Su'],recorded:'Kirjattu',check:'Tarkista',missing:'Puuttuu',week:'Viikko',phases:'työvaihetta',approvalInfo:'hyväksyntä ei vaikuta raportointiin',sendWeek:'Lähetä viikko tarkastettavaksi',editEntry:'Muokkaa kirjausta',addEntry:'Lisää kirjaus',editInfo:'Muutos lähetetään uudelleen työnjohtajan tarkastettavaksi.',addInfo:'Täytä toteutunut työaika jälkikäteen.',cancelEdit:'Peruuta muokkaus',date:'Päivämäärä',worksite:'Työmaa',started:'Alkoi',ended:'Päättyi',littera:'Littera / tehty työ',details:'Lisätieto (valinnainen)',detailsPlaceholder:'Esim. A-talon parvekkeet',saveChanges:'Tallenna muutokset',saveDay:'Tallenna päivä',saveNext:'Tallenna ja lisää toinen työvaihe',saving:'Tallennetaan…',approvedDay:'Päivä on hyväksytty',submittedDay:'Päivä on lähetetty tarkastettavaksi',approvedInfo:'Kirjaukset ovat lukittu.',submittedInfo:'Voit vielä muokata rivejä tai lisätä unohtuneen työvaiheen ennen hyväksyntää.',addAnother:'+ Lisää vielä työvaihe päivälle',dayEntries:'Päivän kirjaukset',workTime:'Työaika',breakDeducted:'Ruokatauko vähennetty automaattisesti 0,50 h',noBreak:'Ei ruokataukovähennystä',edit:'Muokkaa',remove:'Poista',noEntries:'Tälle päivälle ei ole vielä kirjauksia.',statusApproved:'Hyväksytty',statusSubmitted:'Lähetetty',statusReturned:'Palautettu',statusDraft:'Luonnos',selectSiteLittera:'Valitse työmaa ja littera.',endAfterStart:'Päättymisajan pitää olla alkamisajan jälkeen.',overlap:'Kirjaus menee päällekkäin saman päivän aiemman kirjauksen kanssa.',confirmRemove:'Poistetaanko tämä kirjaus?',closed:'suljettu'},
 sq:{worker:'Punonjës',ownHours:'Orët e mia',logout:'Dilni',monthHours:'Orët e pagueshme të muajit',thisMonth:'Ky muaj',weekdays:['Hë','Ma','Më','En','Pr','Sh','Di'],recorded:'Regjistruar',check:'Kontrollo',missing:'Mungon',week:'Java',phases:'faza pune',approvalInfo:'miratimi nuk ndikon në raportim',sendWeek:'Dërgo javën për kontroll',editEntry:'Ndrysho regjistrimin',addEntry:'Shto regjistrim',editInfo:'Ndryshimi dërgohet përsëri për kontroll.',addInfo:'Plotësoni orët e realizuara pas punës.',cancelEdit:'Anulo ndryshimin',date:'Data',worksite:'Kantieri',started:'Filloi',ended:'Përfundoi',littera:'Kodi / puna e bërë',details:'Informacion shtesë (opsional)',detailsPlaceholder:'P.sh. ballkonet e ndërtesës A',saveChanges:'Ruaj ndryshimet',saveDay:'Ruaj ditën',saveNext:'Ruaj dhe shto fazë tjetër',saving:'Duke ruajtur…',approvedDay:'Dita është miratuar',submittedDay:'Dita është dërguar për kontroll',approvedInfo:'Regjistrimet janë të bllokuara.',submittedInfo:'Mund t’i ndryshoni rreshtat ose të shtoni një fazë të harruar para miratimit.',addAnother:'+ Shto fazë tjetër për ditën',dayEntries:'Regjistrimet e ditës',workTime:'Koha e punës',breakDeducted:'Pushimi i drekës 0,50 h është zbritur automatikisht',noBreak:'Pa zbritje të pushimit të drekës',edit:'Ndrysho',remove:'Fshi',noEntries:'Nuk ka ende regjistrime për këtë ditë.',statusApproved:'Miratuar',statusSubmitted:'Dërguar',statusReturned:'Kthyer',statusDraft:'Draft',selectSiteLittera:'Zgjidhni kantierin dhe kodin e punës.',endAfterStart:'Koha e përfundimit duhet të jetë pas fillimit.',overlap:'Regjistrimi mbivendoset me një regjistrim tjetër të ditës.',confirmRemove:'Të fshihet ky regjistrim?',closed:'i mbyllur'},
 en:{worker:'Employee',ownHours:'My hours',logout:'Sign out',monthHours:'Payable hours this month',thisMonth:'This month',weekdays:['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],recorded:'Recorded',check:'Check',missing:'Missing',week:'Week',phases:'work phases',approvalInfo:'approval does not affect reporting',sendWeek:'Send week for review',editEntry:'Edit entry',addEntry:'Add entry',editInfo:'The change will be sent for review again.',addInfo:'Enter completed working hours afterwards.',cancelEdit:'Cancel editing',date:'Date',worksite:'Worksite',started:'Started',ended:'Ended',littera:'Cost code / work performed',details:'Additional details (optional)',detailsPlaceholder:'E.g. Building A balconies',saveChanges:'Save changes',saveDay:'Save day',saveNext:'Save and add another phase',saving:'Saving…',approvedDay:'The day has been approved',submittedDay:'The day has been sent for review',approvedInfo:'The entries are locked.',submittedInfo:'You can still edit rows or add a missing phase before approval.',addAnother:'+ Add another phase to the day',dayEntries:'Entries for the day',workTime:'Working time',breakDeducted:'A 0.50 h meal break was deducted automatically',noBreak:'No meal-break deduction',edit:'Edit',remove:'Delete',noEntries:'No entries for this day yet.',statusApproved:'Approved',statusSubmitted:'Sent',statusReturned:'Returned',statusDraft:'Draft',selectSiteLittera:'Select a worksite and cost code.',endAfterStart:'End time must be after start time.',overlap:'This entry overlaps another entry on the same day.',confirmRemove:'Delete this entry?',closed:'closed'},
 uk:{worker:'Працівник',ownHours:'Мої години',logout:'Вийти',monthHours:'Оплачувані години за місяць',thisMonth:'Цей місяць',weekdays:['Пн','Вт','Ср','Чт','Пт','Сб','Нд'],recorded:'Записано',check:'Перевірити',missing:'Відсутнє',week:'Тиждень',phases:'етапів роботи',approvalInfo:'погодження не впливає на звітність',sendWeek:'Надіслати тиждень на перевірку',editEntry:'Редагувати запис',addEntry:'Додати запис',editInfo:'Зміну буде повторно надіслано на перевірку.',addInfo:'Внесіть фактично відпрацьований час.',cancelEdit:'Скасувати редагування',date:'Дата',worksite:'Об’єкт',started:'Початок',ended:'Кінець',littera:'Код витрат / виконана робота',details:'Додаткова інформація (необов’язково)',detailsPlaceholder:'Напр. балкони будинку A',saveChanges:'Зберегти зміни',saveDay:'Зберегти день',saveNext:'Зберегти й додати інший етап',saving:'Збереження…',approvedDay:'День погоджено',submittedDay:'День надіслано на перевірку',approvedInfo:'Записи заблоковано.',submittedInfo:'До погодження можна редагувати рядки або додати пропущений етап.',addAnother:'+ Додати ще один етап за день',dayEntries:'Записи за день',workTime:'Робочий час',breakDeducted:'Обідню перерву 0,50 год віднято автоматично',noBreak:'Без відрахування обідньої перерви',edit:'Редагувати',remove:'Видалити',noEntries:'За цей день записів ще немає.',statusApproved:'Погоджено',statusSubmitted:'Надіслано',statusReturned:'Повернено',statusDraft:'Чернетка',selectSiteLittera:'Виберіть об’єкт і код витрат.',endAfterStart:'Час закінчення має бути після часу початку.',overlap:'Цей запис перекривається з іншим записом за той самий день.',confirmRemove:'Видалити цей запис?',closed:'закритий'},
};

export const workerText=(language,key)=>texts[language]?.[key]??texts.fi[key]??key;
export const languageLocale=language=>({fi:'fi-FI',sq:'sq-AL',en:'en-GB',uk:'uk-UA'}[language]||'fi-FI');
export const translatedLitteraName=(littera,language)=>({sq:littera?.name_sq,en:littera?.name_en,uk:littera?.name_uk}[language]||littera?.name||'');
